spring:
  datasource:
    driver-class-name: ${env.DB_DRIVER}
    url: ${env.DB_URL}
    username: ${env.DB_USER}
    password: ${env.DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true